### ISSUE TITLE
CARD_HEADER_STYLE

### ISSUE THREAD

**Issue by bramorim** [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex#1]
Hi,

How I set up the CARD_HEADER_STYLE ? Can I put a color?

I need to change de color of square.

Thanks. Bruno.

**Comment by RonnyWeiss** [comment]
Hello

You just can add what you want this is just a css style tag. For example you can add background-color: red; or linear-gradient(60deg, hsl(46, 55%, 60%), hsl(46, 50%, 60%));box-shadow: 0 12px 20px -10px rgba(230, 230, 230, 0.28), 0 4px 20px 0px rgba(0, 0, 0, 0.12), 0 7px 8px -5px rgba(230, 230, 230, 0.2);

It's just up to you!

But to prevent these question in future I will add a better explanation to the plug-in and some examples.

LG Ronny

**Comment by bramorim** [comment]
Thanks!
