### ISSUE TITLE
Region items not supporting 

### ISSUE THREAD

**Issue by moinsultan** [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex#2]
Dear Developer,
its a really nice effort. but i have some issue when i create dashboard and filter some data from one of my page item its showing nothing please take a look and suggest what is the issue .

using apex 5.1, ORDS. theme Material Apex.

here is the querry that is am using

----------------------------------------------
SELECT 'icon' AS CARD_TYPE,
       DECODE(T.STATUS,
              'Open',
              'fa-dropbox',
              'Closed',
              'fa-hand-peace-o',
              'Work In Process',
              'fa-tools') AS CARD_ICON,
       NULL AS CARD_ICON_COLOR,
       NULL AS CARD_HEADER_STYLE,
       T.STATUS AS CARD_TITLE,
       NVL(T.SR_NUMBER, 0) AS CARD_VALUE,
       'This is a Material ' AS CARD_FOOTER,
       NULL AS CARD_LINK,
       NULL AS CARD_CHART_DATA,
       NULL AS CARD_CHART_CONFIG
  FROM (SELECT 'Open' AS STATUS, 1 AS ORD, COUNT(T.SR_NUMBER) AS SR_NUMBER
          FROM TASK_MANAGER_M T
         WHERE T.SR_NUMBER IS NOT NULL
           AND T.ITSM_CATEGORY IS NOT NULL
           AND T.STATUS = 'Open'
        AND T.SR_MANAGER = :P1_NEW
        UNION ALL
        SELECT 'Closed' AS STATUS, 2 AS ORD, COUNT(T.SR_NUMBER) AS SR_NUMBER
          FROM TASK_MANAGER_M T
         WHERE T.SR_NUMBER IS NOT NULL
           AND T.ITSM_CATEGORY IS NOT NULL
           AND T.STATUS = 'Closed'
       AND T.SR_MANAGER = :P1_NEW
        UNION ALL
        SELECT 'Work In Process' AS STATUS,
               3 AS ORD,
               COUNT(T.SR_NUMBER) AS SR_NUMBER
          FROM TASK_MANAGER_M T
         WHERE T.SR_NUMBER IS NOT NULL
           AND T.ITSM_CATEGORY =44
           AND T.STATUS = 'Work In Process'
      AND T.SR_MANAGER = :P1_NEW
       ) T
----------------------------------------------------------
Regards 
Moin Sultan

**Comment by RonnyWeiss** [comment]
Hello 

This is wrong the problem is that the item has no value when the Dashboard Cards start to process. So You need to add the Item before the Dashboard Cards Region on your Apex Page.

I attached an example for this:

![screenshot](https://user-images.githubusercontent.com/30749177/30422431-3ad10d7e-9940-11e7-871d-6b9f85055823.png)

Maybe it helps you, to use: APEX_UTIL.GET_SESSION_STATE in your query. When Session State is null then it's clear why the Dashboard Cards can't work with the Item Value

**Comment by moinsultan** [comment]
why you closed ?? without any update ?

**Comment by RonnyWeiss** [comment]
Hello

Did you read tue Comment above?

Lg

**Comment by moinsultan** [comment]
hi your reply didn't show to me when i checked so thats why i asked. sorry form that.

on the other end i want to filter data on the base of my item in where class in my querry.

WHERE T.SR_NUMBER IS NOT NULL
AND T.ITSM_CATEGORY =44
AND T.STATUS = 'Work In Process'
**AND T.SR_MANAGER = :P1_NEW**
) T

**Comment by moinsultan** [comment]
hi i cant understand these lines.
"The Plug-in submits Items on every ajax call. You just need to add the icon in the "Icon to submit" attribute then you can also manipulate the items on the client with jquery and the new value is used when refresh is fired."

please see attached files then it will more clear to you.

![image](https://user-images.githubusercontent.com/25148453/30639115-0d26006a-9e17-11e7-8d97-7f476880b119.png)
![image](https://user-images.githubusercontent.com/25148453/30639183-48347e3e-9e17-11e7-9d23-02ebc6616dc2.png)
![image](https://user-images.githubusercontent.com/25148453/30639205-62a2dcac-9e17-11e7-86c3-a2d53d7ab29a.png)
