### ISSUE TITLE
Change the HTML

### ISSUE THREAD

**Issue by v1sp** [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex#2]
Hi Ronny,
Classy and awesome plugin
Just wondering is there a way to change the html somehow?
For ex. in the footer I want to add one more line like 
**< span class="pullLeft"> ABC </span>** 
**< span class="pullRight"> ABC </span>**

Or use markup in other places like title, body, footer.. etc
I tried **<b> abc </b>** in footer it was displayed as it is with the tags.

Thanks,
Veerendra.

**Comment by RonnyWeiss** [comment]
Hello Veerendra

Thank you for Feedback! 

Please disable the escape special characters setting in region attributes of the page region. This should help.

Kind regards

Ronny
