### ISSUE TITLE
Add u-color-xx  class for color

### ISSUE THREAD

**Issue by sdembele** [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex#3]
# **Improvement suggestion**
_**Universal Theme provides a number of CSS utility classes that can be used to apply color to any HTML markup.**_
Hi Ronny, for the background colors what do you think about using a color class than using background-color ? So the color will be harmonized with the theme of the application ?

**Comment by RonnyWeiss** [comment]
Will add this feature in next release

**Comment by RonnyWeiss** [comment]
added feature in release 1.4
