### ISSUE TITLE
Card Material

### ISSUE THREAD

**Issue by alhanouf9** [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex#4]
Dear,
This is really absolutely good effort. It's very attractive. I'm a beginner in using apex and I wanted to use it for some queries to generate charts using my data. Could you please advice how to modify it. 
thank you

**Comment by RonnyWeiss** [comment]
Hello

Please take a look on chartist.js website for chart configuration

Kind Regards

Ronny
