### ISSUE TITLE
Image beim CardIcon

### ISSUE THREAD

**Issue by ger88** [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex#4]
Hi,
wie kann ich ein Image im Card Icon einbinden?
Wenn ich ein Bild angebe z.B.  von einer Webseite wird mir nix angezeigt?

**Comment by RonnyWeiss** [comment]
hello

did you download my sample app: https://apex.oracle.com/pls/apex/f?p=103428:14

or did you check my sample statement on that link? There you find how to do it :-)

Have fun with the plug-in

Kind regards

Ronny

**Comment by ger88** [comment]
Hallo Ronny,
ich wollte die App auch installieren, nur verwenden wir noch APEX 18.2 und somit ist die App nicht kompatibel ;-(
Die Beispiele habe ich mir auch alle angeschaut, aber für ein BLOB aus der DB laden gibt es leider kein Beispiel.

Lg,
Gerhard

Von: Ronny Weiss
Gesendet: Montag, 10. August 2020 19:55
An: RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex <Material-Dashboard-Cards-as-HTML-or-for-Apex@noreply.github.com>
Cc: Gerhard Sonntag BOXIT <gerhard.sonntag@boxit.at>; Author <author@noreply.github.com>
Betreff: Re: [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex] Image beim CardIcon (#4)


hello

did you download my sample app: https://apex.oracle.com/pls/apex/f?p=103428:14

or did you check my sample statement on that link? There you find how to do it :-)

Have fun with the plug-in

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
Hallo 

Jetzt verstehe ich das Problem du möchtest als Bild ein BLOB aus der DB haben? Also ja das geht aber nur mit Hilfe von AJAX. Das kann ich dir gern erklären würde die das Weiterhelfen? 

LG Ronny

**Comment by ger88** [comment]
Hallo Ronny,
ja genau das würde ich brauchen, geht das in APEX?
Kannst Du mir beschreiben was ich da machen muss?

Danke, Lg,
Gerhard

Von: Ronny Weiss
Gesendet: Dienstag, 11. August 2020 20:25
An: RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex <Material-Dashboard-Cards-as-HTML-or-for-Apex@noreply.github.com>
Cc: Gerhard Sonntag BOXIT <gerhard.sonntag@boxit.at>; Author <author@noreply.github.com>
Betreff: Re: [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex] Image beim CardIcon (#4)


Hallo

Jetzt verstehe ich das Problem du möchtest als Bild ein BLOB aus der DB haben? Also ja das geht aber nur mit Hilfe von AJAX. Das kann ich dir gern erklären würde die das Weiterhelfen?

LG Ronny

**Comment by RonnyWeiss** [comment]
You need to create a thing like this:

https://oracle-base.com/articles/misc/apex-tips-file-download-from-a-button-or-link

The link that you will create to call the process with 

https://docs.oracle.com/en/database/oracle/application-express/20.1/aeapi/GET_URL-Function.html

you just refer in the icon column of the sql source of the cards like I used it in my example:

SELECT 
       'icon' AS CARD_TYPE, 
       APEX_PAGE.GET_URL (
            p_request => 'APPLICATION_PROCESS=GET_FILE'            
            p_items  => 'FILE_ID',            
            p_values => 'somevalue' ) AS CARD_ICON, 
       NULL AS CARD_ICON_COLOR, 
       NULL AS CARD_HEADER_STYLE,
       NULL AS CARD_HEADER_CLASS,
       'Material Card' AS CARD_TITLE, 
       TO_CHAR(SYSDATE + ROWNUM / 24, 'HH24:MM:SS') AS CARD_VALUE, 
       'This is a Material Card that shows an icon and links to ValueTech' AS CARD_FOOTER, 
       'https://www.valuetech.de/' AS CARD_LINK, 
       NULL AS CARD_CHART_DATA, 
       NULL AS CARD_CHART_CONFIG 
FROM   DUAL

Hope you will all put is together. If nod please ask about more details :-)

Have fun!
